# Generated by Django 2.2.7 on 2020-03-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0002_dream_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='dream_audio',
            field=models.FileField(upload_to='dreams/'),
        ),
    ]
