# Generated by Django 2.2.7 on 2020-03-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0003_auto_20200302_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='dream_audio',
            field=models.FileField(blank=True, upload_to='dreams/'),
        ),
    ]
